Repository Activiti/activiti-examples, pull requests merged in 2018-12, with the labels that each got.

#32 update org.activiti.dependencies:activiti-dependencies to 7.0.65
  activiti-api-basic-full-example/pom.xml
  activiti-api-basic-process-example/pom.xml
  activiti-api-basic-task-example/pom.xml
  activiti-api-spring-integration-example/pom.xml
  activiti-api-web-example/pom.xml
Labels: in progress, updatebot

#35 upgrade to 7.0.67
  activiti-api-basic-full-example/pom.xml
  activiti-api-basic-process-example/pom.xml
  activiti-api-basic-task-example/pom.xml
  activiti-api-basic-task-example/src/main/java/org/activiti/examples/DemoApplication.java
  activiti-api-spring-integration-example/pom.xml
  activiti-api-web-example/pom.xml
Labels: in progress

#36 update org.activiti.dependencies:activiti-dependencies to 7.0.69
  activiti-api-basic-full-example/pom.xml
  activiti-api-basic-process-example/pom.xml
  activiti-api-basic-task-example/pom.xml
  activiti-api-spring-integration-example/pom.xml
  activiti-api-web-example/pom.xml
Labels: in progress, updatebot

#37 update org.activiti.dependencies:activiti-dependencies to 7.0.70
  activiti-api-basic-full-example/pom.xml
  activiti-api-basic-process-example/pom.xml
  activiti-api-basic-task-example/pom.xml
  activiti-api-spring-integration-example/pom.xml
  activiti-api-web-example/pom.xml
Labels: updatebot

#38 update org.activiti.dependencies:activiti-dependencies to 7.0.71
  activiti-api-basic-full-example/pom.xml
  activiti-api-basic-process-example/pom.xml
  activiti-api-basic-task-example/pom.xml
  activiti-api-spring-integration-example/pom.xml
  activiti-api-web-example/pom.xml
Labels: updatebot

#39 update org.activiti.dependencies:activiti-dependencies to 7.0.72
  activiti-api-basic-full-example/pom.xml
  activiti-api-basic-process-example/pom.xml
  activiti-api-basic-task-example/pom.xml
  activiti-api-spring-integration-example/pom.xml
  activiti-api-web-example/pom.xml
Labels: updatebot

#41 update org.activiti.dependencies:activiti-dependencies to 7.0.74
  activiti-api-basic-full-example/pom.xml
  activiti-api-basic-process-example/pom.xml
  activiti-api-basic-task-example/pom.xml
  activiti-api-spring-integration-example/pom.xml
  activiti-api-web-example/pom.xml
Labels: updatebot

#42 update org.activiti.dependencies:activiti-dependencies to 7.0.75
  activiti-api-basic-full-example/pom.xml
  activiti-api-basic-process-example/pom.xml
  activiti-api-basic-task-example/pom.xml
  activiti-api-spring-integration-example/pom.xml
  activiti-api-web-example/pom.xml
Labels: updatebot

#43 update org.activiti.dependencies:activiti-dependencies to 7.0.76
  activiti-api-basic-full-example/pom.xml
  activiti-api-basic-process-example/pom.xml
  activiti-api-basic-task-example/pom.xml
  activiti-api-spring-integration-example/pom.xml
  activiti-api-web-example/pom.xml
Labels: updatebot

#31 show we can use pojos and/or json as json vars
  .gitignore
  activiti-api-basic-full-example-bean/.gitignore
  activiti-api-basic-full-example-bean/.mvn/wrapper/maven-wrapper.jar
  activiti-api-basic-full-example-bean/.mvn/wrapper/maven-wrapper.properties
  activiti-api-basic-full-example-bean/mvnw
  activiti-api-basic-full-example-bean/mvnw.cmd
  activiti-api-basic-full-example-bean/pom.xml
  activiti-api-basic-full-example-bean/src/main/java/org/activiti/examples/Content.java
  activiti-api-basic-full-example-bean/src/main/java/org/activiti/examples/DemoApplication.java
  activiti-api-basic-full-example-bean/src/main/java/org/activiti/examples/DemoApplicationConfiguration.java
  activiti-api-basic-full-example-bean/src/main/java/org/activiti/examples/SecurityUtil.java
  activiti-api-basic-full-example-bean/src/main/resources/application.properties
  activiti-api-basic-full-example-bean/src/main/resources/processes/categorize-human-content.bpmn20.xml
  activiti-api-basic-full-example-bean/src/test/java/org/activiti/examples/DemoApplicationTests.java
  activiti-api-basic-full-example-nobean/.gitignore
  activiti-api-basic-full-example-nobean/mvnw
  activiti-api-basic-full-example-nobean/mvnw.cmd
  activiti-api-basic-full-example-nobean/pom.xml
  activiti-api-basic-full-example-nobean/src/main/java/org/activiti/examples/DemoApplication.java
  activiti-api-basic-full-example-nobean/src/main/java/org/activiti/examples/DemoApplicationConfiguration.java
  activiti-api-basic-full-example-nobean/src/main/java/org/activiti/examples/SecurityUtil.java
  activiti-api-basic-full-example-nobean/src/main/resources/application.properties
  activiti-api-basic-full-example-nobean/src/main/resources/processes/categorize-human-content.bpmn20.xml
  activiti-api-basic-full-example-nobean/src/test/java/org/activiti/examples/DemoApplicationTests.java
  pom.xml
Labels: in progress

#44 update org.activiti.dependencies:activiti-dependencies to 7.0.77
  activiti-api-basic-full-example-bean/pom.xml
  activiti-api-basic-full-example-nobean/pom.xml
  activiti-api-basic-process-example/pom.xml
  activiti-api-basic-task-example/pom.xml
  activiti-api-spring-integration-example/pom.xml
  activiti-api-web-example/pom.xml
Labels: updatebot

#45 update org.activiti.dependencies:activiti-dependencies to 7.0.78
  activiti-api-basic-full-example-bean/pom.xml
  activiti-api-basic-full-example-nobean/pom.xml
  activiti-api-basic-process-example/pom.xml
  activiti-api-basic-task-example/pom.xml
  activiti-api-spring-integration-example/pom.xml
  activiti-api-web-example/pom.xml
Labels: updatebot

#46 update org.activiti.dependencies:activiti-dependencies to 7.0.79
  activiti-api-basic-full-example-bean/pom.xml
  activiti-api-basic-full-example-nobean/pom.xml
  activiti-api-basic-process-example/pom.xml
  activiti-api-basic-task-example/pom.xml
  activiti-api-spring-integration-example/pom.xml
  activiti-api-web-example/pom.xml
Labels: updatebot

#47 update org.activiti.dependencies:activiti-dependencies to 7.0.80
  activiti-api-basic-full-example-bean/pom.xml
  activiti-api-basic-full-example-nobean/pom.xml
  activiti-api-basic-process-example/pom.xml
  activiti-api-basic-task-example/pom.xml
  activiti-api-spring-integration-example/pom.xml
  activiti-api-web-example/pom.xml
Labels: updatebot

#48 update org.activiti.dependencies:activiti-dependencies to 7.0.81
  activiti-api-basic-full-example-bean/pom.xml
  activiti-api-basic-full-example-nobean/pom.xml
  activiti-api-basic-process-example/pom.xml
  activiti-api-basic-task-example/pom.xml
  activiti-api-spring-integration-example/pom.xml
  activiti-api-web-example/pom.xml
Labels: updatebot
